package com.zj.compress;

import android.text.TextUtils;
import android.webkit.MimeTypeMap;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

@SuppressWarnings("unused")
public class Constance {

    static Map<String, String[]> mimeTable;
    static Map<String, String> specialTransferMimeTable;

    public static String getIMEType(String fileName) {
        String type = "*/*";
        int dotIndex = fileName.lastIndexOf(".");
        if (dotIndex < 0) {
            return type;
        }
        String end = fileName.substring(dotIndex).toLowerCase(Locale.ROOT);
        if (TextUtils.isEmpty(end)) {
            return type;
        }
        for (Map.Entry<String, String[]> entry : getMimeTable().entrySet()) {
            if (end.equals(entry.getKey())) {
                type = entry.getValue()[0];
                break;
            }
        }
        return type;
    }

    public static String transformSuffix(String type) {
        for (Map.Entry<String, String[]> e : getMimeTable().entrySet()) {
            for (String s : e.getValue()) {
                if (s.equals(type)) return e.getKey();
            }
        }
        String res;
        res = MimeTypeMap.getSingleton().getExtensionFromMimeType(type);
        if (res == null) {
            try {
                res = "." + type.split("/")[0];
            } catch (Exception ignored) {
            }
        }
        return res == null ? type : res;
    }

    public static Map<String, String[]> getMimeTable() {
        if (mimeTable == null) {
            mimeTable = new HashMap<>();
            mimeTable.put(".3gp", new String[]{"video/3gpp"});
            mimeTable.put(".apk", new String[]{"application/vnd.android.package-archive"});
            mimeTable.put(".asf", new String[]{"video/x-ms-asf"});
            mimeTable.put(".avi", new String[]{"video/x-msvideo", "video/avi"});
            mimeTable.put(".bmp", new String[]{"image/bmp", "application/x-bmp"});
            mimeTable.put(".doc", new String[]{"application/msword"});
            mimeTable.put(".docx", new String[]{"application/vnd.openxmlformats-officedocument.wordprocessingml.document"});
            mimeTable.put(".xls", new String[]{"application/vnd.ms-excel", "application/x-xls"});
            mimeTable.put(".xlsx", new String[]{"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
            mimeTable.put(".*S", new String[]{"application/octet-stream"});
            mimeTable.put(".gif", new String[]{"image/gif"});
            mimeTable.put(".gtar", new String[]{"application/x-gtar"});
            mimeTable.put(".gz", new String[]{"application/x-gzip"});
            mimeTable.put(".html", new String[]{"text/html"});
            mimeTable.put(".jar", new String[]{"application/java-archive"});
            mimeTable.put(".jpeg", new String[]{"image/jpeg", "application/x-jpg", "application/x-jpe"});
            mimeTable.put(".js", new String[]{"application/x-javascript"});
            mimeTable.put(".m3u", new String[]{"audio/x-mpegurl", "audio/mpegurl"});
            mimeTable.put(".m4a", new String[]{"audio/mp4a-latm"});
            mimeTable.put(".m4u", new String[]{"video/vnd.mpegurl"});
            mimeTable.put(".m4v", new String[]{"video/x-m4v"});
            mimeTable.put(".mov", new String[]{"video/quicktime"});
            mimeTable.put(".mp3", new String[]{"audio/x-mpeg", "audio/mp3"});
            mimeTable.put(".aac", new String[]{"audio/aac"});
            mimeTable.put(".mp4", new String[]{"video/mp4"});
            mimeTable.put(".mpc", new String[]{"application/vnd.mpohun.certificate"});
            mimeTable.put(".mpeg", new String[]{"video/x-mpeg", "video/mpg", "video/mpeg"});
            mimeTable.put(".mpga", new String[]{"audio/rn-mpeg", "audio/mpeg"});
            mimeTable.put(".msg", new String[]{"application/vnd.ms-outlook"});
            mimeTable.put(".ogg", new String[]{"audio/ogg"});
            mimeTable.put(".pdf", new String[]{"application/pdf"});
            mimeTable.put(".png", new String[]{"image/png", "application/x-png"});
            mimeTable.put(".pps", new String[]{"application/vnd.ms-powerpoint"});
            mimeTable.put(".ppt", new String[]{"application/vnd.ms-powerpoint", "application/x-ppt"});
            mimeTable.put(".pptx", new String[]{"application/vnd.openxmlformats-officedocument.presentationml.presentation"});
            mimeTable.put(".rmvb", new String[]{"audio/x-pn-realaudio", "application/vnd.rn-realmedia-vbr"});
            mimeTable.put(".ps", new String[]{"application/x-ps", "application/postscript"});
            mimeTable.put(".rtf", new String[]{"application/rtf", "application/x-rtf"});
            mimeTable.put(".tar", new String[]{"application/x-tar"});
            mimeTable.put(".tgz", new String[]{"application/x-compressed"});
            mimeTable.put(".txt", new String[]{"text/plain"});
            mimeTable.put(".wav", new String[]{"audio/x-wav", "audio/wav"});
            mimeTable.put(".wma", new String[]{"audio/x-ms-wma", "audio/x-ms-wma"});
            mimeTable.put(".wmv", new String[]{"audio/x-ms-wmv"});
            mimeTable.put(".tif", new String[]{"application/x-tif", "image/tiff"});
            mimeTable.put(".vsd", new String[]{"application/vnd.visio", "application/x-vsd"});
            mimeTable.put(".vst", new String[]{"application/vnd.visio", "application/x-vst"});
            mimeTable.put(".xml", new String[]{"text/xml"});
            mimeTable.put(".wps", new String[]{"application/vnd.ms-works"});
            mimeTable.put(".z", new String[]{"application/x-compress"});
            mimeTable.put(".zip", new String[]{"application/x-zip-compressed"});
            mimeTable.put(".pem", new String[]{"application/x-pem-file"});
            mimeTable.put(".class", new String[]{"java\\/*"});
            mimeTable.put(".unknown", new String[]{"*/*"});
            mimeTable.put(".001", new String[]{"application/x-001"});
            mimeTable.put(".301", new String[]{"application/x-301"});
            mimeTable.put(".323", new String[]{"text/h323"});
            mimeTable.put(".906", new String[]{"application/x-906"});
            mimeTable.put(".907", new String[]{"drawing/907"});
            mimeTable.put(".a11", new String[]{"application/x-a11"});
            mimeTable.put(".acp", new String[]{"audio/x-mei-aac"});
            mimeTable.put(".ai", new String[]{"application/postscript"});
            mimeTable.put(".aif", new String[]{"audio/aiff"});
            mimeTable.put(".aifc", new String[]{"audio/aiff"});
            mimeTable.put(".aiff", new String[]{"audio/aiff"});
            mimeTable.put(".anv", new String[]{"application/x-anv"});
            mimeTable.put(".asa", new String[]{"text/asa"});
            mimeTable.put(".asp", new String[]{"text/asp"});
            mimeTable.put(".asx", new String[]{"video/x-ms-asf"});
            mimeTable.put(".au", new String[]{"audio/basic"});
            mimeTable.put(".awf", new String[]{"application/vnd.adobe.workflow"});
            mimeTable.put(".biz", new String[]{"text/xml"});
            mimeTable.put(".bot", new String[]{"application/x-bot"});
            mimeTable.put(".c4t", new String[]{"application/x-c4t"});
            mimeTable.put(".c90", new String[]{"application/x-c90"});
            mimeTable.put(".cal", new String[]{"application/x-cals"});
            mimeTable.put(".cat", new String[]{"application/vnd.ms-pki.seccat"});
            mimeTable.put(".cdf", new String[]{"application/x-netcdf"});
            mimeTable.put(".cdr", new String[]{"application/x-cdr"});
            mimeTable.put(".cel", new String[]{"application/x-cel"});
            mimeTable.put(".cer", new String[]{"application/x-x509-ca-cert"});
            mimeTable.put(".cg4", new String[]{"application/x-g4"});
            mimeTable.put(".cgm", new String[]{"application/x-cgm"});
            mimeTable.put(".cit", new String[]{"application/x-cit"});
            mimeTable.put(".cml", new String[]{"text/xml"});
            mimeTable.put(".cmp", new String[]{"application/x-cmp"});
            mimeTable.put(".cmx", new String[]{"application/x-cmx"});
            mimeTable.put(".cot", new String[]{"application/x-cot"});
            mimeTable.put(".crl", new String[]{"application/pkix-crl"});
            mimeTable.put(".crt", new String[]{"application/x-x509-ca-cert"});
            mimeTable.put(".csi", new String[]{"application/x-csi"});
            mimeTable.put(".css", new String[]{"text/css"});
            mimeTable.put(".cut", new String[]{"application/x-cut"});
            mimeTable.put(".dbf", new String[]{"application/x-dbf"});
            mimeTable.put(".dbm", new String[]{"application/x-dbm"});
            mimeTable.put(".dbx", new String[]{"application/x-dbx"});
            mimeTable.put(".dcd", new String[]{"text/xml"});
            mimeTable.put(".dcx", new String[]{"application/x-dcx"});
            mimeTable.put(".der", new String[]{"application/x-x509-ca-cert"});
            mimeTable.put(".dgn", new String[]{"application/x-dgn"});
            mimeTable.put(".dib", new String[]{"application/x-dib"});
            mimeTable.put(".drw", new String[]{"application/x-drw"});
            mimeTable.put(".dtd", new String[]{"text/xml"});
            mimeTable.put(".dwf", new String[]{"Model/vnd.dwf", "application/x-dwf"});
            mimeTable.put(".dwg", new String[]{"application/x-dwg"});
            mimeTable.put(".dxb", new String[]{"application/x-dxb"});
            mimeTable.put(".dxf", new String[]{"application/x-dxf"});
            mimeTable.put(".edn", new String[]{"application/vnd.adobe.edn"});
            mimeTable.put(".emf", new String[]{"application/x-emf"});
            mimeTable.put(".eml", new String[]{"message/rfc822"});
            mimeTable.put(".ent", new String[]{"text/xml"});
            mimeTable.put(".epi", new String[]{"application/x-epi"});
            mimeTable.put(".eps", new String[]{"application/x-ps", "application/postscript"});
            mimeTable.put(".etd", new String[]{"application/x-ebx"});
            mimeTable.put(".fax", new String[]{"image/fax"});
            mimeTable.put(".fdf", new String[]{"application/vnd.fdf"});
            mimeTable.put(".fif", new String[]{"application/fractals"});
            mimeTable.put(".fo", new String[]{"text/xml"});
            mimeTable.put(".frm", new String[]{"application/x-frm"});
            mimeTable.put(".g4", new String[]{"application/x-g4"});
            mimeTable.put(".gbr", new String[]{"application/x-gbr"});
            mimeTable.put(".gl2", new String[]{"application/x-gl2"});
            mimeTable.put(".gp4", new String[]{"application/x-gp4"});
            mimeTable.put(".hgl", new String[]{"application/x-hgl"});
            mimeTable.put(".hmr", new String[]{"application/x-hmr"});
            mimeTable.put(".hpg", new String[]{"application/x-hpgl"});
            mimeTable.put(".hpl", new String[]{"application/x-hpl"});
            mimeTable.put(".hqx", new String[]{"application/mac-binhex40"});
            mimeTable.put(".hrf", new String[]{"application/x-hrf"});
            mimeTable.put(".hta", new String[]{"application/hta"});
            mimeTable.put(".htc", new String[]{"text/x-component"});
            mimeTable.put(".htt", new String[]{"text/webviewhtml"});
            mimeTable.put(".icb", new String[]{"application/x-icb"});
            mimeTable.put(".ico", new String[]{"image/x-icon", "application/x-ico"});
            mimeTable.put(".iff", new String[]{"application/x-iff"});
            mimeTable.put(".ig4", new String[]{"application/x-g4"});
            mimeTable.put(".igs", new String[]{"application/x-igs"});
            mimeTable.put(".iii", new String[]{"application/x-iphone"});
            mimeTable.put(".img", new String[]{"application/x-img"});
            mimeTable.put(".ins", new String[]{"application/x-internet-signup"});
            mimeTable.put(".isp", new String[]{"application/x-internet-signup"});
            mimeTable.put(".IVF", new String[]{"video/x-ivf"});
            mimeTable.put(".la1", new String[]{"audio/x-liquid-file"});
            mimeTable.put(".lar", new String[]{"application/x-laplayer-reg"});
            mimeTable.put(".latex", new String[]{"application/x-latex"});
            mimeTable.put(".lavs", new String[]{"audio/x-liquid-secure"});
            mimeTable.put(".lbm", new String[]{"application/x-lbm"});
            mimeTable.put(".lmsff", new String[]{"audio/x-la-lms"});
            mimeTable.put(".ltr", new String[]{"application/x-ltr"});
            mimeTable.put(".m4e", new String[]{"video/mpeg4"});
            mimeTable.put(".mac", new String[]{"application/x-mac"});
            mimeTable.put(".man", new String[]{"application/x-troff-man"});
            mimeTable.put(".math", new String[]{"text/xml"});
            mimeTable.put(".mdb", new String[]{"application/msaccess", "application/x-mdb"});
            mimeTable.put(".mfp", new String[]{"application/x-shockwave-flash"});
            mimeTable.put(".mht", new String[]{"message/rfc822"});
            mimeTable.put(".mhtml", new String[]{"message/rfc822"});
            mimeTable.put(".mi", new String[]{"application/x-mi"});
            mimeTable.put(".mid", new String[]{"audio/mid"});
            mimeTable.put(".midi", new String[]{"audio/mid"});
            mimeTable.put(".mil", new String[]{"application/x-mil"});
            mimeTable.put(".mml", new String[]{"text/xml"});
            mimeTable.put(".mnd", new String[]{"audio/x-musicnet-download"});
            mimeTable.put(".mns", new String[]{"audio/x-musicnet-stream"});
            mimeTable.put(".movie", new String[]{"video/x-sgi-movie"});
            mimeTable.put(".mp1", new String[]{"audio/mp1"});
            mimeTable.put(".mp2", new String[]{"audio/mp2"});
            mimeTable.put(".mpa", new String[]{"video/x-mpg"});
            mimeTable.put(".mpd", new String[]{"application/vnd.ms-project"});
            mimeTable.put(".mpp", new String[]{"application/vnd.ms-project"});
            mimeTable.put(".mpt", new String[]{"application/vnd.ms-project"});
            mimeTable.put(".mpw", new String[]{"application/vnd.ms-project"});
            mimeTable.put(".mpx", new String[]{"application/vnd.ms-project"});
            mimeTable.put(".mtx", new String[]{"text/xml"});
            mimeTable.put(".mxp", new String[]{"application/x-mmxp"});
            mimeTable.put(".net", new String[]{"image/pnetvue"});
            mimeTable.put(".nrf", new String[]{"application/x-nrf"});
            mimeTable.put(".nws", new String[]{"message/rfc822"});
            mimeTable.put(".odc", new String[]{"text/x-ms-odc"});
            mimeTable.put(".out", new String[]{"application/x-out"});
            mimeTable.put(".p10", new String[]{"application/pkcs10"});
            mimeTable.put(".p12", new String[]{"application/x-pkcs12"});
            mimeTable.put(".p7b", new String[]{"application/x-pkcs7-certificates"});
            mimeTable.put(".p7c", new String[]{"application/pkcs7-mime"});
            mimeTable.put(".p7m", new String[]{"application/pkcs7-mime"});
            mimeTable.put(".p7r", new String[]{"application/x-pkcs7-certreqresp"});
            mimeTable.put(".p7s", new String[]{"application/pkcs7-signature"});
            mimeTable.put(".pc5", new String[]{"application/x-pc5"});
            mimeTable.put(".pci", new String[]{"application/x-pci"});
            mimeTable.put(".pcl", new String[]{"application/x-pcl"});
            mimeTable.put(".pcx", new String[]{"application/x-pcx"});
            mimeTable.put(".pdx", new String[]{"application/vnd.adobe.pdx"});
            mimeTable.put(".pfx", new String[]{"application/x-pkcs12"});
            mimeTable.put(".pgl", new String[]{"application/x-pgl"});
            mimeTable.put(".pic", new String[]{"application/x-pic"});
            mimeTable.put(".pko", new String[]{"application/vnd.ms-pki.pko"});
            mimeTable.put(".pl", new String[]{"application/x-perl"});
            mimeTable.put(".pls", new String[]{"audio/scpls"});
            mimeTable.put(".plt", new String[]{"application/x-plt"});
            mimeTable.put(".pot", new String[]{"application/vnd.ms-powerpoint"});
            mimeTable.put(".ppa", new String[]{"application/vnd.ms-powerpoint"});
            mimeTable.put(".ppm", new String[]{"application/x-ppm"});
            mimeTable.put(".pr", new String[]{"application/x-pr"});
            mimeTable.put(".prf", new String[]{"application/pics-rules"});
            mimeTable.put(".prn", new String[]{"application/x-prn"});
            mimeTable.put(".prt", new String[]{"application/x-prt"});
            mimeTable.put(".ptn", new String[]{"application/x-ptn"});
            mimeTable.put(".pwz", new String[]{"application/vnd.ms-powerpoint"});
            mimeTable.put(".r3t", new String[]{"text/vnd.rn-realtext3d"});
            mimeTable.put(".ra", new String[]{"audio/vnd.rn-realaudio"});
            mimeTable.put(".ram", new String[]{"audio/x-pn-realaudio"});
            mimeTable.put(".ras", new String[]{"application/x-ras"});
            mimeTable.put(".rat", new String[]{"application/rat-file"});
            mimeTable.put(".rdf", new String[]{"text/xml"});
            mimeTable.put(".rec", new String[]{"application/vnd.rn-recording"});
            mimeTable.put(".red", new String[]{"application/x-red"});
            mimeTable.put(".rgb", new String[]{"application/x-rgb"});
            mimeTable.put(".rjs", new String[]{"application/vnd.rn-realsystem-rjs"});
            mimeTable.put(".rjt", new String[]{"application/vnd.rn-realsystem-rjt"});
            mimeTable.put(".rlc", new String[]{"application/x-rlc"});
            mimeTable.put(".rle", new String[]{"application/x-rle"});
            mimeTable.put(".rm", new String[]{"application/vnd.rn-realmedia"});
            mimeTable.put(".rmf", new String[]{"application/vnd.adobe.rmf"});
            mimeTable.put(".rmi", new String[]{"audio/mid"});
            mimeTable.put(".rmj", new String[]{"application/vnd.rn-realsystem-rmj"});
            mimeTable.put(".rmm", new String[]{"audio/x-pn-realaudio"});
            mimeTable.put(".rmp", new String[]{"application/vnd.rn-rn_music_package"});
            mimeTable.put(".rms", new String[]{"application/vnd.rn-realmedia-secure"});
            mimeTable.put(".rmx", new String[]{"application/vnd.rn-realsystem-rmx"});
            mimeTable.put(".rnx", new String[]{"application/vnd.rn-realplayer"});
            mimeTable.put(".rp", new String[]{"image/vnd.rn-realpix"});
            mimeTable.put(".rpm", new String[]{"audio/x-pn-realaudio-plugin"});
            mimeTable.put(".rsml", new String[]{"application/vnd.rn-rsml"});
            mimeTable.put(".rt", new String[]{"text/vnd.rn-realtext"});
            mimeTable.put(".rv", new String[]{"video/vnd.rn-realvideo"});
            mimeTable.put(".sam", new String[]{"application/x-sam"});
            mimeTable.put(".sat", new String[]{"application/x-sat"});
            mimeTable.put(".sdp", new String[]{"application/sdp"});
            mimeTable.put(".sdw", new String[]{"application/x-sdw"});
            mimeTable.put(".sit", new String[]{"application/x-stuffit"});
            mimeTable.put(".slb", new String[]{"application/x-slb"});
            mimeTable.put(".sld", new String[]{"application/x-sld"});
            mimeTable.put(".slk", new String[]{"drawing/x-slk"});
            mimeTable.put(".smi", new String[]{"application/smil"});
            mimeTable.put(".smil", new String[]{"application/smil"});
            mimeTable.put(".smk", new String[]{"application/x-smk"});
            mimeTable.put(".snd", new String[]{"audio/basic"});
            mimeTable.put(".sol", new String[]{"text/plain"});
            mimeTable.put(".sor", new String[]{"text/plain"});
            mimeTable.put(".spc", new String[]{"application/x-pkcs7-certificates"});
            mimeTable.put(".spl", new String[]{"application/futuresplash"});
            mimeTable.put(".spp", new String[]{"text/xml"});
            mimeTable.put(".ssm", new String[]{"application/streamingmedia"});
            mimeTable.put(".sst", new String[]{"application/vnd.ms-pki.certstore"});
            mimeTable.put(".stl", new String[]{"application/vnd.ms-pki.stl"});
            mimeTable.put(".sty", new String[]{"application/x-sty"});
            mimeTable.put(".svg", new String[]{"text/xml"});
            mimeTable.put(".swf", new String[]{"application/x-shockwave-flash"});
            mimeTable.put(".tdf", new String[]{"application/x-tdf"});
            mimeTable.put(".tg4", new String[]{"application/x-tg4"});
            mimeTable.put(".tga", new String[]{"application/x-tga"});
            mimeTable.put(".tiff", new String[]{"image/tiff"});
            mimeTable.put(".tld", new String[]{"text/xml"});
            mimeTable.put(".top", new String[]{"drawing/x-top"});
            mimeTable.put(".torrent", new String[]{"application/x-bittorrent"});
            mimeTable.put(".tsd", new String[]{"text/xml"});
            mimeTable.put(".uin", new String[]{"application/x-icq"});
            mimeTable.put(".uls", new String[]{"text/iuls"});
            mimeTable.put(".vcf", new String[]{"text/x-vcard"});
            mimeTable.put(".vda", new String[]{"application/x-vda"});
            mimeTable.put(".vdx", new String[]{"application/vnd.visio"});
            mimeTable.put(".vml", new String[]{"text/xml"});
            mimeTable.put(".vpg", new String[]{"application/x-vpeg005"});
            mimeTable.put(".vss", new String[]{"application/vnd.visio"});
            mimeTable.put(".vsw", new String[]{"application/vnd.visio"});
            mimeTable.put(".vsx", new String[]{"application/vnd.visio"});
            mimeTable.put(".vtx", new String[]{"application/vnd.visio"});
            mimeTable.put(".vxml", new String[]{"text/xml"});
            mimeTable.put(".wax", new String[]{"audio/x-ms-wax"});
            mimeTable.put(".wb1", new String[]{"application/x-wb1"});
            mimeTable.put(".wb2", new String[]{"application/x-wb2"});
            mimeTable.put(".wb3", new String[]{"application/x-wb3"});
            mimeTable.put(".wbmp", new String[]{"image/vnd.wap.wbmp"});
            mimeTable.put(".wiz", new String[]{"application/msword"});
            mimeTable.put(".wk3", new String[]{"application/x-wk3"});
            mimeTable.put(".wk4", new String[]{"application/x-wk4"});
            mimeTable.put(".wkq", new String[]{"application/x-wkq"});
            mimeTable.put(".wks", new String[]{"application/x-wks"});
            mimeTable.put(".wm", new String[]{"video/x-ms-wm"});
            mimeTable.put(".wmd", new String[]{"application/x-ms-wmd"});
            mimeTable.put(".wmf", new String[]{"application/x-wmf"});
            mimeTable.put(".wml", new String[]{"text/vnd.wap.wml"});
            mimeTable.put(".wmx", new String[]{"video/x-ms-wmx"});
            mimeTable.put(".wmz", new String[]{"application/x-ms-wmz"});
            mimeTable.put(".wp6", new String[]{"application/x-wp6"});
            mimeTable.put(".wpd", new String[]{"application/x-wpd"});
            mimeTable.put(".wpg", new String[]{"application/x-wpg"});
            mimeTable.put(".wpl", new String[]{"application/vnd.ms-wpl"});
            mimeTable.put(".wq1", new String[]{"application/x-wq1"});
            mimeTable.put(".wr1", new String[]{"application/x-wr1"});
            mimeTable.put(".wri", new String[]{"application/x-wri"});
            mimeTable.put(".wrk", new String[]{"application/x-wrk"});
            mimeTable.put(".ws", new String[]{"application/x-ws"});
            mimeTable.put(".ws2", new String[]{"application/x-ws"});
            mimeTable.put(".wsc", new String[]{"text/scriptlet"});
            mimeTable.put(".wsdl", new String[]{"text/xml"});
            mimeTable.put(".wvx", new String[]{"video/x-ms-wvx"});
            mimeTable.put(".xdp", new String[]{"application/vnd.adobe.xdp"});
            mimeTable.put(".xdr", new String[]{"text/xml"});
            mimeTable.put(".xfd", new String[]{"application/vnd.adobe.xfd"});
            mimeTable.put(".xfdf", new String[]{"application/vnd.adobe.xfdf"});
            mimeTable.put(".xlw", new String[]{"application/x-xlw"});
            mimeTable.put(".xpl", new String[]{"audio/scpls"});
            mimeTable.put(".xq", new String[]{"text/xml"});
            mimeTable.put(".xql", new String[]{"text/xml"});
            mimeTable.put(".xquery", new String[]{"text/xml"});
            mimeTable.put(".xsd", new String[]{"text/xml"});
            mimeTable.put(".xsl", new String[]{"text/xml"});
            mimeTable.put(".xslt", new String[]{"text/xml"});
            mimeTable.put(".xwd", new String[]{"application/x-xwd"});
            mimeTable.put(".x_b", new String[]{"application/x-x_b"});
            mimeTable.put(".sis", new String[]{"application/vnd.symbian.install"});
            mimeTable.put(".sisx", new String[]{"application/vnd.symbian.install"});
            mimeTable.put(".x_t", new String[]{"application/x-x_t"});
            mimeTable.put(".ipa", new String[]{"application/vnd.iphone"});
            mimeTable.put(".xap", new String[]{"application/x-silverlight-app"});
        }
        return mimeTable;
    }
}